version: "3.9"
services:
  repository:
    build:
      context: .
      dockerfile: dockerfile.db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "taskmanagementsystem"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: password
    container_name: db